### ISSUE TITLE
nach reboot kein WebApiSync

### ISSUE THREAD

**Issue by XSDiVer** [iobroker-community-adapters/ioBroker.nuki-extended#105]
Bin nicht sicher ob es an der Token Verschlüsselung lag - habe alles neu eingerichtet, jetzt ging es erstmal.
Aber nach einem reboot vom Raspi 4 bekomme ich "webapisync" nicht mehr auf "true".

Ich verstehe einfach nicht warum :o(

**Comment by XSDiVer** [comment]
Ich habe jetzt nochmal ein wenig getestet. Wenn ich den Adapter drei mal in kurzen Abständen hintereinander starte,
bekommt er den WebApiSync auf "true" gesetzt. Wenn ich nur 2 mal oder 4 mal neu starte bleibt der WebApiSync auf "false" und somit geht nichts. 

Ich hab mir da jetzt eine Script gebastelt, das nach einem Neustart den Adapter 3x neu startet nachdem der Raspi mit ioBroker hoch gefahren ist. Das scheint erstmal zu funktionieren. Ne tolle Lösung ist das zwar nicht, aber solange es funktikoniert.

Ich hatte auch ioBroker komplett neu aufgesetzt auf eine leere SSD und NUR den Nuki Extended installiert,
da hatte ich leider das gleiche Problem - scheint also nicht an meiner ioBroker installation zu liegen.

Hab auch die Bridge auf Werkseinstellungen zurück gesetzt - desöfteren, weil ich dachte es geht vielleicht dann.

War leider auch Fehlanzeige. Bin auch nicht sicher ob es an dem Adapter liegt, vielleicht hat auch die Bridge einen Schaden,
aber über die App sowie über den WebAccount lässt sich alles ohne Probleme bedienen.

Vielen Dank.

**Comment by Grothesk242** [comment]
Passt evtl. zu diesem Issue. 
Seit kurzem (beobachtet seit dem Upgrade auf die Beta-Version vom js-controller 3.2.6-0 (und node: v14.15.4)) startet der Adapter nicht mehr bei einem start/restart des ioBrokers von sich aus hoch sondern braucht noch eine 'Extra-Einladung' per manuellem Neustart (Klick auf den 'Neu laden'-Button).

**Comment by RP70DP** [comment]
Kann das Verhalten bestätigen. Ebenfalls vermute ich einen Zusammenhang mit dem neuen JS-Controller 3.2.6-X.

**Comment by FlexerJR** [comment]
Bei mir kann ich auch bestätigen, das kein WbAPI Sync mehr stattfindet. Lief problemlos bis letzte Woche seit dem keine Verbindung mehr

![image](https://user-images.githubusercontent.com/40354380/173176361-df46632f-0dbd-4eba-98d5-11e14607206e.png)

**Comment by mcm1957** [comment]
Falls das Problem mit der aktuellsten Release (2.6.5) noch auftritt bitte ein neues Issue mit den minimalen Versionsinfos anlegen:

Adapter Version:
js-controller Version:
Node Version:
