### ISSUE TITLE
Nuki opener knopf im Homekit

### ISSUE THREAD

**Issue by misterT33** [iobroker-community-adapters/ioBroker.nuki-extended#106]
Hallo ihr lieben. Ich bin leider kein Programmierer, veruche mich aber hier durchzuschlagen. Klappt auch ganz gut . Aber ich bekomme einfach nicht den opener mit Yahka in Apple Homekit integriert. 

Kann mir jemand helfen?

Ich weis einfach nicht was ich wie wo anklicken muss

Wäre megaaaa

Danke

**Comment by Baenker** [comment]
Ich habe den Opener in Yahka eingetragen.

In Kurzform: Ich habe einen State erstellt als booelan. Diesen State habe ich als Steckdose in Yahka angelegt. Beim einschalten über Yahka wird dieser State auf true gesetzt. Ein Script reagiert darauf und setzt den Wert zum einen wieder auf false und zum anderen löst er den Opener aus, so dass der Summer geht.

Ich denke das ist kein Issue und hört hier nicht hin. Für solche Fragen gibt es das Forum

**Comment by Baenker** [comment]
@mcm1957 hier kannst Du auch zu machen wenn Du gerade am aufräumen bist

**Comment by mcm1957** [comment]
Danke,
Ja bin ein wenig am Aufräumen. Hab keine Ahnung ob / wer eine echte Maintanence machen kann / wird.
Aber die Issue Leichen bringen niemand was.

DANKE für die Rückmeldung
