### ISSUE TITLE
frage: webapi intervall

### ISSUE THREAD

**Issue by krobipd** [iobroker-community-adapters/ioBroker.nuki-extended#108]
Hallo und entschuldige bitte gleich meine vl doofe Frage.

ich frage mich welche Einstellungen/Informationen eigentlich von der WebAPI geholt werden bzw welche bei dieser Intervall einstellungen/informationen überhaupt aktualisiert werden? habe ja eine hardware bridge, inwiefern sind diese Infos anders als die die Bridge sowieso liefert?

![Screenshot 2020-11-26 180951](https://user-images.githubusercontent.com/27220902/100377986-a3c3e100-3012-11eb-9010-2a6cc9fb01bd.png)

**Comment by Baenker** [comment]
Die Info steht in der Readme (such mal nach "with Nuki Web API")
Bei 0 werden die Infos nur beim Adapterstart geholt.
