### ISSUE TITLE
Nachtmodus aktivieren

### ISSUE THREAD

**Issue by mcbirne** [iobroker-community-adapters/ioBroker.nuki-extended#115]
Man kann den Nachtmodus (Nuki-extended.0.smartlocks.[smartlockname].state.nightMode) auf true setzen aber das hat keine Auswirkung.

**Comment by Zefau** [comment]
wahrscheinlich wegen https://github.com/Zefau/ioBroker.nuki-extended/issues/59. Schau mal im Nuki Web (online Webseite), ob die Änderung dort wirklich nicht angekommen ist.

**Comment by mcbirne** [comment]
Ich habe Version 2.3 installiert. Die Einstellung vom Nachtmodus hat keine Auswirkung auf das Nuki Web. Ich kann ihn nicht aktivieren und auch nicht deaktivieren.

Das Schloss aufschließen klappt aber. Daher denke ich, dass der Adapter erstmal richtig eingerichtet ist.

**Comment by mcbirne** [comment]
Könnte der Fehler reproduziert werden?

**Comment by mcm1957** [comment]
Falls das Problem mit der aktuellsten Release (2.6.5) noch auftritt bitte ein neues Issue mit den minimalen Versionsinfos anlegen:

Adapter Version:
js-controller Version:
Node Version:
