### ISSUE TITLE
Adapter erkennt "Tür geöffnet" nicht

### ISSUE THREAD

**Issue by LortusX** [iobroker-community-adapters/ioBroker.nuki-extended#121]
Bei unseren beiden Nukis wird der Status "Tür geöffnet" korrekt in der App sowie auf dem Webinterface angezeigt - im Adapter bleiben beim Öffnen alle Werte unverändert. Ich gehe davon aus, dass der "doorState" als "Current door-state of the Nuki" dann eigentlich nicht mehr als "DOOR_CLOSED(2)" gelistet sein dürfte, da der Türsensor gemä0 der anderen Anzeigen korrekt funktioniert. Ein Offenhalten der Türen ~5min brachte keine Veränderung.

**Comment by mcbirne** [comment]
Das sollte an einer Einstellung leigen. Bei mir funktioniert das korrekt.

**Comment by mcm1957** [comment]
Falls das Problem mit der aktuellsten Release (2.6.5) noch auftritt bitte ein neues Issue mit den minimalen Versionsinfos anlegen:

Adapter Version:
js-controller Version:
Node Version:
