### ISSUE TITLE
Status werden nicht zuverlässig aktualisiert

### ISSUE THREAD

**Issue by firebowl** [iobroker-community-adapters/ioBroker.nuki-extended#144]
Hi,
erstmal super Adapter, dafür!
Ich habe allerdings ein Problem und weiß nicht ob es an deinem Adapter liegt oder am Nuki bzw. der Bridge.

Bei mir wird der Wert von z.B. lastAction nicht aktualisiert wenn er sich nicht ändert.
Er steht z.B. auf 3 also Unlatch mit 7:18 am 13.05., um diese Zeit wurde heute früh das erste mal die Tür geöffnet also der Status hat sich von 0 über 1 nach 3 geändert.
Wenn ich jetzt die Tür wieder von außen öffne, müsste der aktuelle Status 3 wieder mit 3 überschrieben werden und der Timestamp auf z.B. 10:00 am 13.05. geändert werden. Es passiert jedoch nichts und somit kann ich auf den Datenpunkt nicht prüfen weil er sich nicht mehr ändert bis ich zusperre.
Wäre es möglich den Timestamp neu zu schreiben wenn der Status auf den gleichen Status "geändert" wird? Also Unlatch zum nächsten Unlatch?
Ich bin sicher nicht der Einzige, der seine Haustür öfter mal öffnet ohne sie vorher komplett zu und wieder aufzusperren.

**Comment by Baenker** [comment]
Dafür kannst Du den Türsensor nehmen. Der ändert sich immer von Tür auf und Tür zu. Unabhängig ob das Schloß verändert wird.

**Comment by firebowl** [comment]
Leider bringt mir das nix weil der Sensor ja auch triggert wenn ich die Tür von innen öffne und rausgehe. 
Mir geht es ja darum, dass sich z.B. ein Licht einschaltet wenn die Tür geöffnet wurde.

**Comment by Baenker** [comment]
Das wird Dir auch nichts bringen weil das ganze zu langsam wäre. Und Sinn und Zweck einer Lampe ist doch wenn es dunkel ist das die Lampe an geht. Ich fände es auf jeden Fall nur bei sehr wenigen Datenpunkten sinnvoll das der Timestamp sich ändert. Jede Änderung erzeugt Last.

**Comment by imes217** [comment]
Hallo,

ich benutze auch Deinen Nuki Adapter, danke dafür.
Leider wird der LockState nicht aktualisiert. Siehe Screenshot.
Was mache ich falsch?
![image](https://user-images.githubusercontent.com/44963000/144622459-3e632b35-2175-4839-9170-1855b6cdb15d.png)

**Comment by mcm1957** [comment]
Warum sollte dich der Lockstate von 3 auf 3 "ändern"?
Du schreibst ja selbst, dass die Türe nicht versperrt wurde. 

Ich she hier kein Problem.
