### ISSUE TITLE
admin 5.x 

### ISSUE THREAD

**Issue by arteck** [iobroker-community-adapters/ioBroker.nuki-extended#145]
![grafik](https://user-images.githubusercontent.com/6681528/118170206-1c382600-b42a-11eb-9c06-3bcc44784a98.png)

**Comment by Grothesk242** [comment]
https://github.com/Zefau/ioBroker.nuki-extended/issues/132

**Comment by Apollon77** [comment]
duplicate, and also js.controller related and not admin5, try github version
