### ISSUE TITLE
Lock/Unlock Switch

### ISSUE THREAD

**Issue by mproper23** [iobroker-community-adapters/ioBroker.nuki-extended#164]
Would it be possible to add the Option as in the "Simple" Nuki adapter that you can switch between Lock/Unlock?

**Comment by Baenker** [comment]
Dies ist der nuki-extended Adapter und dort gibt es die gewünschte Funktion. Für den anderen Adapter entsprechend Issue dort einstellen.

Bitte Issue schließen

**Comment by Baenker** [comment]
@mcm1957 das hat sich auch erledigt und sollte geschlossen werden
