### ISSUE TITLE
Lockstate wird nicht aktualisiert LastStateUpdate findet nicht statt.

### ISSUE THREAD

**Issue by imes217** [iobroker-community-adapters/ioBroker.nuki-extended#170]
Hallo,

ich benutze auch Deinen Nuki Adapter, danke dafür.
Leider werden alle States, so z.B. der "LockState" nicht aktualisiert, Wie auch (Siehe Screenshot) der "LastStateUpdate" richtigerweise anzeigt. 

![image](https://user-images.githubusercontent.com/44963000/144622459-3e632b35-2175-4839-9170-1855b6cdb15d.png)

_Originally posted by @imes217 in https://github.com/iobroker-community-adapters/ioBroker.nuki-extended/issues/144#issuecomment-985584192_

**Comment by Baenker** [comment]
Mal ehrlich wer soll hiermit was anfangen können. Da werden schon mehr Infos benötigt und vermutlich auch Debug-Logs? 

Ich probiere es mal: Beim Opener wird das Feld bei mir richtig aktualisiert. Ich vermute also es wird das Nuki-Türschloss sein? Welche Version? Wird eine Bridge benutzt?

Bei mir aktualisiert sich der Statur bei dem Schloss mit Bridge auch nicht bzw es steht auf ein altes Datum. Könnte bei mir trotzdem stimmen. Könnte das Datum sein wo ich zum letzten mal die Tür zugeschlossen habe. Was ich eigentlich so gut wie nie mache. Für mich persönlich ist das Feld aber auch nicht interessant. Testen kann ich derzeit nicht da ich das Türschloss derzeit nicht nutzen kann. 

Hauptproblem für Dich: Adapter wird eigentlich nicht mehr richtig gepflegt…

**Comment by mcm1957** [comment]
Sollte das Problem noch mit der aktuellsten Version (2.6.5) auftreten, bitte ein neues Issue anlegen mit:

Version of adapter:
Js-controlelr Version:
Node Version:

Log Auszug
