### ISSUE TITLE
Adapter Settings not useable in darkmode

### ISSUE THREAD

**Issue by theimo1221** [iobroker-community-adapters/ioBroker.nuki-extended#245]
**Describe the bug**  
As visible in the screenshot below, it is not possible to use the settings while Dark Mode is active

**To Reproduce**  
1. Activate Dark color scheme
2. Go to instance settings (e.g. for Web Api)

**Expected behavior**  
Settings useable

**Screenshots & Logfiles**  
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/20605452/170890382-93513421-a2a2-4dd1-a94f-3841f5d353e3.png">

**Versions:**  
 - Adapter version: 2.4.0
 - JS-Controller version: 5.4.9
 - Node version: 16.15.0
 - Operating system: Linux (Proxmox)

**Comment by simatec** [comment]
Fix in next Version
