### ISSUE TITLE
Kompatibel mit Smartlock 3.0 Pro?

### ISSUE THREAD

**Issue by docugraf** [iobroker-community-adapters/ioBroker.nuki-extended#254]
Hallo, 
kann man das SmartLock 3.0 Pro (incl. WiFi) ohne Bridge mit deinem Adapter nutzen?

**Comment by tmycgn** [comment]
Würde mich auch interessieren, jetzt wo die 3.0 Pro Version wieder lieferbar ist. :)

**Comment by Scotty-89** [comment]
Hey,

ich habe ein und nachdem ich für

"Intervall in Sekunden, nach dem alle Einstellungen / Informationen aktualisiert werden. Wenn auf 0 eingestellt, werden Einstellungen nur bei einem Adapter-Start aktualisiert."

ein Wert >5 (also 5) eingetragen hab läuft es auch. Als ich dort 0 drin hatte ging da nichts, es wurden auch keine Werte abgerufen etc. ich hatte lediglich den Info baum mit Connection true.

**Comment by mcm1957** [comment]
Frage wurde offensichtlich von @Scotty-89 schon beantwortet.
