### ISSUE TITLE
Settings im dark mode

### ISSUE THREAD

**Issue by docugraf** [iobroker-community-adapters/ioBroker.nuki-extended#274]
Darstellung im io-Broker-Darkmode  der Settings passen nicht, Schriften bleiben weiss auf weissem Hintergrund

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/104724022/208140856-898a359e-633c-418b-a024-62f73aaf25fd.png)
![grafik](https://user-images.githubusercontent.com/104724022/208140889-ec2d521e-9dbb-486e-a04d-318826708e8d.png)

**Versions:**  
 - Adapter version: nuki-extended.0  v2.3.1
 - JS-Controller version: 4.0.23
 - Node version: 16.15.1
 - Operating system: Raspi / Win10

**Additional context**

**Comment by mcm1957** [comment]
no more info - so lets close.

Please open a new issue and provide the requested data if the problem still exists.
