### ISSUE TITLE
Delayed Updates of Door Sensor after replacing Nuki Smartlock 3.0

### ISSUE THREAD

**Issue by MarkusKress** [iobroker-community-adapters/ioBroker.nuki-extended#286]
Due to a defect of my Nuki Smartlock 3.0 with this Adapter in Version 2.6.5. I replace dem Smartlock with an other one (same Locktype). I've delete the old device from Nuki-App and configured all things again (Gateway, Keypad, Door sensor). All things are running well like before, except the Adapter. I've got most of the states immediately (unlatched or door opened), but not door closed. I've checked the door sensor, but it's correctly installed. I can see the correct state in the Nuki App, but not in IOBroker. After some Minutes or Hours. It seems, opening the App it triggers the update, but not every time. Any ideas what's append here?

I've replaced both auth keys, only to be sure there was nothing changed at Nuki side. Version of Adapter, js-controlelr or node havn't been changed between Smartlock exchange. I'm sure it's not Adapter problem, because all other other functions works well, but I have no idea anymore.

In parallel I've opened a ticket at nuki, because there is also a delay (and missing) states from door sensor. I've sent two screenshots 30 min. after I've closed the door. In App you see the closed door event in nuki web not. 

I've deleted the nuki api key in the adapter to find out, if the adapter using at first the nuki web, but it's still missing or delayed.

Adapter Version: 2.6.5
js-controller: 4.0.24
node-Version: v18.16.0

**Comment by mcm1957** [comment]
Please add the minimum reuired version info to ANY issue:
Adapter version:
js-controller version:
node-version:

**Comment by MarkusKress** [comment]
Also the API shows the incorrect door state. So it's not a bug or an issue of the adapter.

**Comment by mcm1957** [comment]
Thanks for feedback
