### ISSUE TITLE
Please activate Nuki Web API to retrieve log entries

### ISSUE THREAD

**Issue by DrBakterius** [iobroker-community-adapters/ioBroker.nuki-extended#298]
Ich habe mein Nuki 3.0 pro, besser gesagt Web Nuki, mit dem Adapter verbunden indem ich ein API Token erstellt und im Adapter eingetragen habe. Daraufhin wurden alle Datenpunkte angelegt und ich kann das Nuki damit steuern.

Will ich aber die Log-Entries (über http://192.168.*.*:8082/nuki-extended/index.html) aufrufen, dann erhalte ich nach einigen Sekunden statt der Meldung **_Loading log entries.._** nur den Hinweis **_Please activate Nuki Web API to retrieve log entries!_**

Beim API Token sind alle Rechte erteilt, also auch für das Log. Mit einem Nuki 2.0 das ich zuvor hatte, hat das noch funktioniert. Da hatte ich aber eine Bridge die ich beim Nuki 3.0 pro ja nicht mehr benötige. Online kann ich das Log aufrufen, also vorhanden ist es, nur der Adapter ruft es offensichtlich nicht ab.

**Comment by oswaldo-be** [comment]
got the same problem... or do we have to activate extended Web-API integration?

**Comment by mcm1957** [comment]
**Please add missing version infos:**

adapter:
js-controller:
admin:
node:
o/s:

**Comment by DrBakterius** [comment]
adapter: **v2.6.5**
js-controller: **v5.0.12**
admin: **v6.10.1**
node: **v18.17.1**
o/s: **debian 12 bookworm**

**Comment by oswaldo-be** [comment]
> **Please add missing version infos:**
> 
> adapter:v2.6.5
>  js-controller: 5.0.12
> admin:  6.10.1
> node: v18.17.1
> o/s: Ubuntu 22.04.3 LTS

**Comment by DrBakterius** [comment]
> [auf 5 gestellt und Zack, habe ich Einträge...](https://github.com/iobroker-community-adapters/ioBroker.nuki-extended/issues/254#issuecomment-1191869965)

Das habe ich schon länger so eingestellt und die Datenpunkte werden so relativ schnell aktualisiert, aber trotzdem kein Log.

**Comment by DrBakterius** [comment]
Fehler gefunden!?

Im WEB-Adapter darf bei der _socket.io Instanz_ nur '**_integriert_**' ausgewählt sein. Mit '_**ws**_' (Web Socket Adapter) funktioniert das Log nicht.

**Comment by mischmi66** [comment]
> Fehler gefunden!?
> 
> Im WEB-Adapter darf bei der _socket.io Instanz_ nur '**_integriert_**' ausgewählt sein. Mit '_**ws**_' (Web Socket Adapter) funktioniert das Log nicht.

Danke Dir! Made my day ....Genau das war der Fehler

**Comment by mcm1957** [comment]
Lt. letztem Eintrag scheitn das Problem behoben zu sein,
Falls nicht, bitte ggF ein neues Issue erstellen.
