### ISSUE TITLE
States are not updated when only nuki bridge ist configurated

### ISSUE THREAD

**Issue by dagr1709** [iobroker-community-adapters/ioBroker.nuki-extended#302]
Hello,

 I dont want to use the web api, so i only configurate the nuki bridge.

I can lock and unlock when i use the action button.
But the states are not updated. Only when i restart the adapter.

**Comment by mcm1957** [comment]
Please add complete version information:

adapter:
js-controller:
admin:
node:
o/s:

and attach a log of the instance with log level debug.

**Comment by mcm1957** [comment]
no more info - so lets close.

Please open a new issue and provide the requested data if the problem still exists.
