### ISSUE TITLE
State data points are not updated

### ISSUE THREAD

**Issue by Johannes200658** [iobroker-community-adapters/ioBroker.nuki-extended#318]
Only the "_nuki-extended.0.smartlocks.wohnungstuer.state.lastDataUpdate_" data point is updated regularly, which is every 30 seconds. All other data points below "_nuki-extended.0.smartlocks.wohnungstuer.state_" only update sporadically and are therefore very unreliable. Only when I operate the SmartLock via IoBroker do the statuses change immediately. When I open or close the door via the app, the status doesn't always change.
Hardware Nuki 4.0 pro over Web API.
Greetings, John

**Comment by mcm1957** [comment]
Please add complete version information:

adapter:
js-controller:
admin:
node:
o/s:

and attach a log of the instance with log level debug.

**Comment by mcm1957** [comment]
no more info - so lets close.

Please open a new issue and provide the requested data if the problem still exists.
