### ISSUE TITLE
Instance can't be installed with js-controller 6.x / Admin 7.x.x (?)

### ISSUE THREAD

**Issue by Horgul123** [iobroker-community-adapters/ioBroker.nuki-extended#341]
When trying to add a new instance with js-controller 6.x and web 6.2.6 you get

`Latest available version of "web" is required, but nothing installed. Please install first "web" and then retry.
Latest available version of "js-controller" is required, but nothing installed. Please install first "js-controller" and then retry.`

**Comment by mcm1957** [comment]
This is for sure NO problem of the adapter.

Most likely you have installed admin 7.x.x. This behaviour is a now bug of admin 7.x.x - see https://github.com/ioBroker/ioBroker.admin/issues/2497. Admin 7.x.x has been revoked. Please install current LATEST Release of admin (6.x.x) and retry.

If Installation stil fails please report the problem at the js-contoller 6 discussion topic to further diagnose the problem.
https://forum.iobroker.net/topic/75206/beta-test-js-controller-kiera-v6-0

In any case please attach logfile and reposrt ALL relevant versions (Adapter, js.controller, admin, node, O/S

**Comment by Horgul123** [comment]
@mcm1957 Yes, I have installed Admin 7.x Thanks for the hint, I just saw the error and thought it's caused by the adapter

**Comment by mcm1957** [comment]
Please let us know if problem is fixed after downgrade and eventually close this issue in that case.

**Comment by Horgul123** [comment]
@mcm1957 works after downgrade. Thanks
