### ISSUE TITLE
Multiple warnings in iobroker log (TLS, 403, Bad Gateway)

### ISSUE THREAD

**Issue by devit-at** [iobroker-community-adapters/ioBroker.nuki-extended#382]
I got multiple warnings on my iobroker log regarding getWebApi();

getWebApi(): Error retrieving notifications: Error: Client network socket disconnected before secure TLS connection was established

getWebApi(): Error retrieving smartlocks: 403 - "403 Forbidden"	

getWebApi(): Error retrieving notifications: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

getWebApi(): Error retrieving smartlocks: 429 - "<html>\r\n<head><title>429 Too Many Requests</title></head>\r\n<body>\r\n<center><h1>429 Too Many Requests</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

I'm using iobroker web on a secure connection (SSL / https)

This happens when i start the adapter. However, i can access the log webinterface on port 8082 but only via http

iobroker runs on a raspberry pi 4, Version of the adapter is 2.7.0

**Comment by mcm1957** [comment]
siehe auch https://forum.iobroker.net/topic/78153/nuki-extended-fehler-web-api

**Comment by mcm1957** [comment]
Das Problem hat sich lt. Forumsbeiträgen behoben.
