### ISSUE TITLE
Updates from Nuki Web API are not reflected correctly

### ISSUE THREAD

**Issue by Zefau** [iobroker-community-adapters/ioBroker.nuki-extended#59]
See https://forum.iobroker.net/post/388718

**Comment by Zefau** [comment]
Also https://forum.iobroker.net/post/390265

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.nuki-extended/issues/66#issuecomment-655737133:
> I compared the activity log in ioBroker and in the Nuki Web. They are the same but stopped this morning with the last entry at 11:50. The Nuki app shows the full activity log, last entry Lock at 22:00. This confirms your conclusion.

**Comment by fabiankrauss** [comment]
Hallo @Zefau ,
ich wollte nur kurz zurückmelden, dass ich seit kurzem die Android Bridge nutze und auch das beschriebene Problem hatte, dass ich keine Aktionen ausführen konnte (Stand: 2.2.5). Nach es etwas Issues lesen, bin ich auf deinen Hinweis 2.2.6 zu testen gestoßen.
Habe gerade mal über die "Katze" 2.2.6 geladen und es hat sofort geklappt. Ich werde jetzt auf 2.2.5 wieder zurückspringen,  mach aber aktuell keine Probleme bei mir.
Wann denkst du, wirst du 2.2.6 releasen?

Danke dir für die tolle Arbeit! 
Viele Grüße 
Fabian

**Comment by Zefau** [comment]
Dachte das hätte ich schon. Hab's nun nachgeholt.

**Comment by fabiankrauss** [comment]
@Zefau  Danke klappt :)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.nuki-extended/issues/66#issuecomment-655728875
> Could you try both via smartphone app and via Nuki Web (https://web.nuki.io) ? Is both not working for you?
> 
> I'm facing the same issue, but apparently it looks like the smartphone app is not syncing with Nuki Web. Nuki Web though is correctly syncing with ioBroker.

https://github.com/Zefau/ioBroker.nuki-extended/issues/66#issuecomment-655737133
> I compared the activity log in ioBroker and in the Nuki Web. They are the same but stopped this morning with the last entry at 11:50. The Nuki app shows the full activity log, last entry Lock at 22:00. This confirms your conclusion.

**Comment by mcm1957** [comment]
Falls das Problem mit der aktuellsten Release (2.6.5) noch auftritt bitte ein neues Issue mit den minimalen Versionsinfos anlegen:

Adapter Version:
js-controller Version:
Node Version:
