### ISSUE TITLE
Last Code entered on keypad?

### ISSUE THREAD

**Issue by FlexerJR** [iobroker-community-adapters/ioBroker.nuki-extended#76]
Hi Dev, thanks for your work with Nuki!

I have a question. Is it possible to extract the last code entered on the keypad in one datapoint?

Thanks ;)

**Comment by Zefau** [comment]
short answer: I don't think so.

long answer: I don't own a keypad myself. As I was reading in the documentation online, Nuki handles a keypad like a user. This generally means you can synchronize the users via Web API.
Though, this only provide the following information:
![image](https://user-images.githubusercontent.com/14368811/87707166-f954cb00-c7a0-11ea-8c30-096ccd3ed50f.png)

**Comment by FlexerJR** [comment]
Ok thanks for that quick reply. I'm just trying to figure out, which was the last code, fob or person opening the door. 
I think there are two ways. Monitoring of the number of valid entries Datapoint lockcount. If the number is rising the user must be the last, or by parsing the history log...

**Comment by Zefau** [comment]
What about `datelastActive` ?

**Comment by FlexerJR** [comment]
Well, was my second try but the states are not updating on time. I'm pressing the fob for example and there is no update on the state. The only state with an update on time is the log history and the states of the Smartlock itself. Some weird behavior.

**Comment by FlexerJR** [comment]
Hi Zefau, I‘m still fighting with the adapter. There are several settings for updating the state. I would love to get all datapoints updated in a set interval?

Best regards

**Comment by Zefau** [comment]
What's your exact problem? The `lockState` is updated by the callback (in case it has been set correctly) via Bridge API. Most of the other states are updated by the poll interval via Web API.

**Comment by Zefau** [comment]
Please also note https://github.com/Zefau/ioBroker.nuki-extended/issues/59#issuecomment-663211971
Smartphone changes are sometimes not synchronized to the Nuki servers, which means that ioBroker states the wrong values.
Try to change directly on Nuki Web.

**Comment by Zefau** [comment]
@FlexerJR Do you have any news or more specific details on this?

**Comment by FlexerJR** [comment]
I‘m just on buisness travel. Can tell you more when I‘m back home.

**Comment by FlexerJR** [comment]
Hi Zefau, I'm back again. Ok first of all thanks for your hard work on this adapter. 

I tried to figure out a solution but I'm out of ideas.
My idea was to get information of which user is taking which action in the system.
I'm parsing the log. I found out that 
action 1 is unlocking
action 2 is locking
action 3 is opening the door. 

The name of the user is behind name:"User"

This approach is good and working BUT the History isn't updating on time and skipping actions.
I'm opening by hand --> Log is changing --> Trigger works
I'm closing by hand --> Log is changing --> Trigger works
I'm opening by hand --> Log is changing --> Trigger works
But after some time the log isn't changing nor updating even if I open by Keypad or something. 
After this ice works for 3-4 times and after that the log is skipping a action in the system. 

I don't know if this is connected to the other issue you mentioned above.

Here a screenshot of the blocky 
<img width="342" alt="Bildschirmfoto 2020-08-01 um 22 19 34" src="https://user-images.githubusercontent.com/40354380/89109849-2366e800-d445-11ea-881e-9e9769ecffba.png">

If I open the door by lets say a fob and I try to take this user as trigger it isn't working. The states under users are not updating on time as well.

Best regards...

**Comment by Zefau** [comment]
@FlexerJR any news on this? how do we proceed?

**Comment by FlexerJR** [comment]
Well my script is working but sometimes the actual state of nuki is not in sync with the log. That means if a code is opening the door via the keypad i get the correct message and on a other day the message is skiped. 

I have now idea how to fix it because i think its a problem of the nuki server. 

Do you have any ideas?

**Comment by mcm1957** [comment]
I'll close here as this discussion seems to be outdated.
