### ISSUE TITLE
Klingelunterdrückung (de)aktivieren

### ISSUE THREAD

**Issue by Zefau** [iobroker-community-adapters/ioBroker.nuki-extended#91]

**Comment by Zefau** [comment]
Ich habe vergessen, warum ich diesen Feature Request geöffnet habe.

Eine Klingelunterdrückung sollte via `openerAdvancedConfig.doorbellSuppression` möglich sein.

**Comment by EddyDsSmartHome** [comment]
Hallo Zefau, wie per Mail schon geschrieben würde ich die Klingelunterdrückung gerne über den ioBroker steuern.
Würde mich freuen wenn das machbar ist.
Mein Hintergedanken ist, das ist das ganze über ein Blockly nachts aktivieren und morgens deaktiviere.
Bzw. ich habe bei mir einen Monitor an der Wand/Tür montiert über den ich meine smartes Zuhause steuere und wenn mein kleiner mal Mittagsschlaf macht würde ich die klinge gerne deaktivieren, in der Nuki App ist die Funktion ja sehr tief im Menü versteckt und etwas nervig dahin zu navigieren.
über die Vis wäre das sehr einfach, zumindest bei mir dann :) 
Würde mich sehr freuen wenn du das in den Adapter integrieren könntest, also einen Datenpunkt dafür bereitstellen könntest.

Vielen Dank
Gruß
Eddy

**Comment by Zefau** [comment]
Hast du die Web API aktiviert? Damit sollte es gehen. Du kannst dann die Datenpunkt der Konfiguration bearbeiten, z. B. `openerAdvancedConfig.doorbellSuppression`. Hast du das schon probiert?

**Comment by EddyDsSmartHome** [comment]
Hi, nein noch nicht getestet. 
Habe nur deinen Adapter installiert kurz darübergeschaut, dir gedankt (wird glaube ich zu selten gemacht) und mein Kommentar hinterlassen. 
Hatte noch keine Zeit da weiter rein zu schauen, habe sowas zwar noch nicht gemacht, hört sich jetzt aber nicht so an als wäre es sehr schwer.
Werde es mal am Wochenende testen, würde es aber dennoch bevorzugen wenn es in dem Adapter ist, jetzt nicht nur für mich sondern für die ungeübten unter uns .
Vielen Dank aber für die Info.

**Comment by EddyDsSmartHome** [comment]
> Hast du die Web API aktiviert? Damit sollte es gehen. Du kannst dann die Datenpunkt der Konfiguration bearbeiten, z. B. `openerAdvancedConfig.doorbellSuppression`. Hast du das schon probiert?

OK Web API ist aktiviert, aber verstehe nicht wie und wo ich die Datenpunkte erzeugen kann?
Kannst du das etwas für Leute erklären die damit nicht jeden Tag zu tun haben ;)

**Comment by Zefau** [comment]
Siehe auch https://github.com/Zefau/ioBroker.nuki-extended#nuki-web-api

Hast du den Web API Key / Schlüssel im Adapter hinterlegt? Dann sollten die Datenpunkte automatisch erscheinen, insbesondere ein Channel mit `openerAdvancedConfig`.

**Comment by EddyDsSmartHome** [comment]
Musste den Adapter löschen und neu installieren dann ist der Ordner aufgetaucht.
Der war vorher nicht da obwohl API Schlüssel hinterlegt war (hatten den Key heute nachträglich hinzugefügt und Adapter mehrfach neu gestartet)
Danke für die Rückmeldung.

**Comment by Baenker** [comment]
Aus meiner sicht geht das ganze sehr zuverlässig. Ich stelle die Klingel immer auf Lautlos per Script wenn meine Frau und ich beide die Homezone verlassen. Wenn einer die Homezone betritt wird die Klingel wieder aktiviert. Funktioniert bei mir schon sehr sehr lange ohne Probleme.

**Comment by Baenker** [comment]
@mcm1957 hier bitte auch zu machen.
