### ISSUE TITLE
Keine History Liste mehr wegen angeblich fehlendem API

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.nuki-extended#92]
Ich bekomme unter 2.3.0 keine Histroy Anzeige mehr, mit dem Hinweis, das ich den WEB API Key aktivieren soll.
Dieser ist aber aktiviert. Ich habe ihn sogar gelöscht, neu erstellt und wieder eingetragen und gespeichert. Trotzdem kommt wieder der Hinweis das der Web API Key aktiviert werden muss.

Sind aktuell irgend welche Probleme in dieser Richtung bekannt?

![2020-09-23 12_19_24-ioBroker nuki-extended](https://user-images.githubusercontent.com/44617472/94000180-1ad0c500-fd97-11ea-9971-f24b79d251e7.png)

**Comment by Azathoth88** [comment]
Bei mir werden Daten dargestellt.

**Comment by JackDaniel007** [comment]
das selbe hab ich nun bei beiden bridges :(

**Comment by Dragon0501** [comment]
Selbes Problem!

**Comment by JBSullivan** [comment]
Mit dem neusten Update aus dem latest (2.3.0), ist zumindest bei mir der Fehler weg und die Liste wieder dargestellt.
