### ISSUE TITLE
Einstellungen unter openerAdvancedConfig werden nicht aktualisiert

### ISSUE THREAD

**Issue by Azathoth88** [iobroker-community-adapters/ioBroker.nuki-extended#94]
Die openerAdvancedConfig sind bei mir prinizpiell verfügbar. Allerdings werden die Werte nicht synchronisiert.

Beispiel:
Ich habe bisher bei Tastendruck auf den Opener die Klingel ausgelöst.
Also singleButtonPressAction = OPEN(7)

In der App habe ich nun umgestellt, dass bei Tastendruck nichts passieren soll.
Erwartungsgemäß sollte nun der Adapter sich umstellen - spätestens nachdem der Adapter neugestartet wurde.

**Comment by EddyDsSmartHome** [comment]
ist bei mir auch so, habe noch keine Lösung gefunden, schon alles mögliche versucht. meine letzte Zeitstempel Aktualisierung war am 22.9

**Comment by EddyDsSmartHome** [comment]
> Die openerAdvancedConfig sind bei mir prinizpiell verfügbar. Allerdings werden die Werte nicht synchronisiert.
> 
> Beispiel:
> Ich habe bisher bei Tastendruck auf den Opener die Klingel ausgelöst.
> Also singleButtonPressAction = OPEN(7)
> 
> In der App habe ich nun umgestellt, dass bei Tastendruck nichts passieren soll.
> Erwartungsgemäß sollte nun der Adapter sich umstellen - spätestens nachdem der Adapter neugestartet wurde.

Bist du weiter gekommen, hast du den Fehler gefunden?

**Comment by Zefau** [comment]
Aus meiner Sicht ein Fehler bei Nuki nicht im Adapter, weil die API nicht aktualisiert.

Stell mal bitte die Instanz auf Debug, dann erscheinen die empfangenen Werte als json im Log. Die sind schon falsch.

**Comment by Zefau** [comment]
Siehe auch https://github.com/Zefau/ioBroker.nuki-extended/issues/59

**Comment by mcm1957** [comment]
Falls das Problem mit der aktuellsten Release (2.6.5) noch auftritt bitte ein neues Issue mit den minimalen Versionsinfos anlegen:

Adapter Version:
js-controller Version:
Node Version:
